name: Run Bot Telegram

on: 
  schedule:
    branches:
      - master
    - cron: '20 4,14,22 * * *'
  release:
    branches:
      - master
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: pip install -r requirements.txt
    - name: Run bot.py
      run: python bot.py
      env:
        TELEGRAM_ACCESS_TOKEN: ${{ secrets.TELEGRAM_ACCESS_TOKEN }}
